/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 14-Sep-2024 4:51:43 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Produccion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Produccion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Inventario_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventario] DROP CONSTRAINT [FK_Inventario_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Nomina_Empleado_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Nomina] DROP CONSTRAINT [FK_Nomina_Empleado_02]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordencompra_Producto]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordencompra] DROP CONSTRAINT [FK_Ordencompra_Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Ordencompra_Proveedore_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Ordencompra] DROP CONSTRAINT [FK_Ordencompra_Proveedore_02]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Produccion_Animale_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Produccion] DROP CONSTRAINT [FK_Produccion_Animale_02]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[IXFK_Produccion_Animale]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Produccion] DROP CONSTRAINT [IXFK_Produccion_Animale]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto] DROP CONSTRAINT [FK_Producto_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Venta_Animale_02]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Venta] DROP CONSTRAINT [FK_Venta_Animale_02]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Venta_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Venta] DROP CONSTRAINT [FK_Venta_Cliente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Animale]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Animale]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Nomina]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Nomina]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Ordencompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Ordencompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Produccion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Produccion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Proveedore]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Proveedore]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Venta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Venta]
GO

/* Create Tables */

CREATE TABLE [Animale]
(
	[ID_animale] int NOT NULL,
	[Tipo] varchar(50) NOT NULL,
	[Fecha_Nacimiento] date NULL,
	[Peso_Actual] decimal(8) NULL,
	[Produccion_Leche] decimal(8) NULL
)
GO

CREATE TABLE [Cliente]
(
	[ID_cliente] int NOT NULL IDENTITY (1, 1),    -- atributo que relaciona 
	[nombre_a] varchar(100) NOT NULL,
	[direccion_a] varchar(150) NULL,
	[telefono_a] varchar(15) NULL,
	[correo_a] varchar(100) NULL
)
GO

CREATE TABLE [Empleado]
(
	[ID_empleado] int NOT NULL IDENTITY (1, 1),
	[Nombre_l] varchar(100) NOT NULL,
	[Salario_l] decimal(10) NOT NULL,
	[Bonificacion_l] decimal(10) NULL,
	[Fecha_Contratacion] date NOT NULL,
	[Cargo_l] varchar(50) NOT NULL,
	[ID_produccion] int NULL
)
GO

CREATE TABLE [Inventario]
(
	[ID_inventario] int NOT NULL IDENTITY (1, 1),
	[ID_producto] int NOT NULL,
	[cantidad_d] decimal(10) NOT NULL,
	[Fecha_Ingreso] date NOT NULL
)
GO

CREATE TABLE [Nomina]
(
	[ID_nomina] int NOT NULL IDENTITY (1, 1),
	[ID_empelado] int NOT NULL,
	[salario_r] decimal(10) NOT NULL,
	[Fecha_Pago] date NOT NULL,
	[bonificaciones_r] decimal(10) NULL,
	[ID_empleado] int NULL
)
GO

CREATE TABLE [Ordencompra]
(
	[ID_orden] int NOT NULL,
	[ID_proveerdore] int NOT NULL,
	[ID_producto] int NOT NULL,
	[cantidad_k] decimal(12) NOT NULL,
	[Fecha_Orden] date NOT NULL,
	[Total_Orden] decimal(10) NOT NULL,
	[ID_proveedore] int NULL
)
GO

CREATE TABLE [Produccion]
(
	[ID_produccion] int NOT NULL IDENTITY (1, 1),
	[ID_animale] int NOT NULL,
	[Cantidad_Leche] decimal(10) NOT NULL,
	[Fecha_Produccion] date NOT NULL
)
GO

CREATE TABLE [Producto]
(
	[ID_producto] int NOT NULL IDENTITY (1, 1),
	[Tipo_Producto] varchar(50) NOT NULL,
	[Descripcion] varchar(150) NULL,
	[Precio_Venta] decimal(10) NOT NULL,
	[ID_cliente] int NULL
)
GO

CREATE TABLE [Proveedore]
(
	[ID_proveedore] int NOT NULL,
	[nombre_f] varchar(100) NOT NULL,
	[direccion_f] varchar(150) NULL,
	[telefono_f] varchar(15) NULL,
	[correo_f] varchar(100) NULL
)
GO

CREATE TABLE [Venta]
(
	[ID_venta] int NOT NULL IDENTITY (1, 1),
	[ID_cliente] int NOT NULL,
	[ID_producto] int NOT NULL,
	[Cantidad] decimal(10) NOT NULL,
	[Fecha_Venta] date NOT NULL,
	[Total_Venta] decimal(12) NOT NULL,
	[ID_animale] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Animale] 
 ADD CONSTRAINT [PK_Animale]
	PRIMARY KEY CLUSTERED ([ID_animale] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_clientes ]
	PRIMARY KEY CLUSTERED ([ID_cliente] ASC)
GO

ALTER TABLE [Empleado] 
 ADD CONSTRAINT [PK_Empleado]
	PRIMARY KEY CLUSTERED ([ID_empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado_Produccion] 
 ON [Empleado] ([ID_produccion] ASC)
GO

ALTER TABLE [Inventario] 
 ADD CONSTRAINT [PK_Inventario]
	PRIMARY KEY CLUSTERED ([ID_inventario] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Inventario_Producto] 
 ON [Inventario] ([ID_producto] ASC)
GO

ALTER TABLE [Nomina] 
 ADD CONSTRAINT [PK_Nomina]
	PRIMARY KEY CLUSTERED ([ID_nomina] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Nomina_Empleado] 
 ON [Nomina] ([ID_empleado] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Nomina_Empleado_02] 
 ON [Nomina] ([ID_empleado] ASC)
GO

ALTER TABLE [Ordencompra] 
 ADD CONSTRAINT [PK_Ordencompra]
	PRIMARY KEY CLUSTERED ([ID_orden] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Ordencompra_Producto] 
 ON [Ordencompra] ([ID_producto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Ordencompra_Proveedore] 
 ON [Ordencompra] ([ID_proveedore] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Ordencompra_Proveedore_02] 
 ON [Ordencompra] ([ID_proveedore] ASC)
GO

ALTER TABLE [Produccion] 
 ADD CONSTRAINT [PK_Produccion]
	PRIMARY KEY CLUSTERED ([ID_produccion] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Produccion_Animale_02] 
 ON [Produccion] ([ID_animale] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([ID_producto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Producto_Cliente] 
 ON [Producto] ([ID_cliente] ASC)
GO

ALTER TABLE [Proveedore] 
 ADD CONSTRAINT [PK_Proveedore]
	PRIMARY KEY CLUSTERED ([ID_proveedore] ASC)
GO

ALTER TABLE [Venta] 
 ADD CONSTRAINT [PK_Venta]
	PRIMARY KEY CLUSTERED ([ID_venta] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Venta_Animale] 
 ON [Venta] ([ID_animale] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Venta_Animale_02] 
 ON [Venta] ([ID_animale] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Venta_Cliente] 
 ON [Venta] ([ID_cliente] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Produccion]
	FOREIGN KEY ([ID_produccion]) REFERENCES [Produccion] ([ID_produccion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventario] ADD CONSTRAINT [FK_Inventario_Producto]
	FOREIGN KEY ([ID_producto]) REFERENCES [Producto] ([ID_producto]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Nomina] ADD CONSTRAINT [FK_Nomina_Empleado_02]
	FOREIGN KEY ([ID_empleado]) REFERENCES [Empleado] ([ID_empleado]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordencompra] ADD CONSTRAINT [FK_Ordencompra_Producto]
	FOREIGN KEY ([ID_producto]) REFERENCES [Producto] ([ID_producto]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Ordencompra] ADD CONSTRAINT [FK_Ordencompra_Proveedore_02]
	FOREIGN KEY ([ID_proveedore]) REFERENCES [Proveedore] ([ID_proveedore]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Produccion] ADD CONSTRAINT [FK_Produccion_Animale_02]
	FOREIGN KEY ([ID_animale]) REFERENCES [Animale] ([ID_animale]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Produccion] ADD CONSTRAINT [IXFK_Produccion_Animale]
	FOREIGN KEY ([ID_animale]) REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_Cliente]
	FOREIGN KEY ([ID_cliente]) REFERENCES [Cliente] ([ID_cliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Venta] ADD CONSTRAINT [FK_Venta_Animale_02]
	FOREIGN KEY ([ID_animale]) REFERENCES [Animale] ([ID_animale]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Venta] ADD CONSTRAINT [FK_Venta_Cliente]
	FOREIGN KEY ([ID_cliente]) REFERENCES [Cliente] ([ID_cliente]) ON DELETE No Action ON UPDATE No Action
GO

/* Create Table Comments */


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Animale', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Tabla donde se ve informacion de animales', 'SCHEMA', 'dbo', 'table', 'Animale' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Tabla donde se ve informacion de animales', 'SCHEMA', 'dbo', 'table', 'Animale' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Cliente', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Tabla donde se lleva registro de clientes ', 'SCHEMA', 'dbo', 'table', 'Cliente' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Tabla donde se lleva registro de clientes ', 'SCHEMA', 'dbo', 'table', 'Cliente' 
end

EXEC sp_addextendedproperty 'MS_Description', 'atributo que relaciona ', 'Schema', [dbo], 'table', [Cliente], 'column', [ID_cliente]
GO

if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'TABLE', 'Cliente', 'CONSTRAINT', 'PK_clientes ')) 
   begin 
 	EXEC sys.sp_updateextendedproperty 'MS_Description', 'Llave primaria de la tabla', 'SCHEMA', 'dbo', 'TABLE', 'Cliente', 'CONSTRAINT', 'PK_clientes ' 
   end 
 else 
   begin 
 	EXEC sys.sp_addextendedproperty    'MS_Description', 'Llave primaria de la tabla', 'SCHEMA', 'dbo', 'TABLE', 'Cliente', 'CONSTRAINT', 'PK_clientes ' 
   end 

GO


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Empleado', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Todo sobre empleados ', 'SCHEMA', 'dbo', 'table', 'Empleado' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Todo sobre empleados ', 'SCHEMA', 'dbo', 'table', 'Empleado' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Inventario', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Tabla donde se llevan los inventarios', 'SCHEMA', 'dbo', 'table', 'Inventario' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Tabla donde se llevan los inventarios', 'SCHEMA', 'dbo', 'table', 'Inventario' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Nomina', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'informacion de nomina', 'SCHEMA', 'dbo', 'table', 'Nomina' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'informacion de nomina', 'SCHEMA', 'dbo', 'table', 'Nomina' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Produccion', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'tabla donde se lleva la produccion ', 'SCHEMA', 'dbo', 'table', 'Produccion' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'tabla donde se lleva la produccion ', 'SCHEMA', 'dbo', 'table', 'Produccion' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Producto', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Productos granja el pino', 'SCHEMA', 'dbo', 'table', 'Producto' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Productos granja el pino', 'SCHEMA', 'dbo', 'table', 'Producto' 
end

if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'TABLE', 'Producto', 'CONSTRAINT', 'PK_Producto')) 
   begin 
 	EXEC sys.sp_updateextendedproperty 'MS_Description', 'Informacion de productos de la granja', 'SCHEMA', 'dbo', 'TABLE', 'Producto', 'CONSTRAINT', 'PK_Producto' 
   end 
 else 
   begin 
 	EXEC sys.sp_addextendedproperty    'MS_Description', 'Informacion de productos de la granja', 'SCHEMA', 'dbo', 'TABLE', 'Producto', 'CONSTRAINT', 'PK_Producto' 
   end 

GO


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Proveedore', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'informacion de proveedore', 'SCHEMA', 'dbo', 'table', 'Proveedore' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'informacion de proveedore', 'SCHEMA', 'dbo', 'table', 'Proveedore' 
end


GOif exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'table', 'Venta', NULL, NULL)) 
begin 
  EXEC sys.sp_updateextendedproperty 'MS_Description', 'Tablas donde se llevan las ventas ', 'SCHEMA', 'dbo', 'table', 'Venta' 
end 
else 
begin 
  EXEC sys.sp_addextendedproperty 'MS_Description', 'Tablas donde se llevan las ventas ', 'SCHEMA', 'dbo', 'table', 'Venta' 
end

if exists (select * from ::fn_listextendedproperty ('MS_Description', 'SCHEMA', 'dbo', 'TABLE', 'Venta', 'CONSTRAINT', 'PK_Venta')) 
   begin 
 	EXEC sys.sp_updateextendedproperty 'MS_Description', 'Informacion de ventas', 'SCHEMA', 'dbo', 'TABLE', 'Venta', 'CONSTRAINT', 'PK_Venta' 
   end 
 else 
   begin 
 	EXEC sys.sp_addextendedproperty    'MS_Description', 'Informacion de ventas', 'SCHEMA', 'dbo', 'TABLE', 'Venta', 'CONSTRAINT', 'PK_Venta' 
   end 

GO
